# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.5
loader_version=0.17.2

#Fabric api
fabric_version=0.92.6+1.20.1

# Mod Properties
mod_version = 1.3.4
maven_group = io.github.ladysnake
archives_base_name = impaled

#Other Dependencies
findbugs_version = 3.0.2
jb_annotations_version = 15.0
apiguardian_version = 1.0.0
vanguard_version = 1.0.+

#Publishing
owners = Ladysnake
license_header = ARR
curseforge_id = 478843
curseforge_versions = 1.20.1
cf_requirements = fabric-api
release_type = release
modrinth_id = AiHAhIP5

#Compat
#Arsenal
reach_entity_attributes_version=2.4.0
arsenal_version=0.1.5-1.20.1
ratatouille_version=1.0.9-1.20.1

#Enchancement testing
enchancement_version=1.20-26
cardinal_components_version=5.2.2
midnightlib_version=1.4.1-fabric
step_height_entity_attribute_version=25dabcdad7
tooltipfix_version=1.1.1-1.20
apoli_version=2.9.0
architectury_version=9.1.12
geckolib_version=1.20.1:4.3.1
sodium_version=mc1.20.1-0.5.3
spectrum_version=1.7.8
mod_menu_version=7.2.2
mixin_squared_version=0.1.2-beta.6
